# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YouTube-api-Alamofire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YouTube-api-Alamofire

pod 'Alamofire', '~> 5.4'
pod 'Nuke'

  target 'YouTube-api-AlamofireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YouTube-api-AlamofireUITests' do
    # Pods for testing
  end

end
